import type { BusinessTaxonomyEntry } from "./contracts";

// F7.1: Business Taxonomy -- unica fuente de verdad para clasificar
// lenguaje natural de negocio. Nunca se dispersa en ifs sueltos ni en
// diccionarios paralelos (regla explicita del PO) -- el interprete
// (intent-interpreter.ts) SOLO lee de este arreglo, nunca tiene su
// propio vocabulario embebido.
//
// crmIndustryBucket es null quando ninguna Industry real del CRM (hoy:
// Construction, Warehouse/Logistics, Manufacturing, General Labor --
// ver docs/F7_CEO_INTELLIGENCE_AND_AUTONOMOUS_CLIENT_ACQUISITION_PLAN.md
// §1.7) es un match razonable. Crear una Industry real nueva
// (Hospitality, Healthcare, etc.) es una decision de F5/F6 territory,
// fuera de alcance de F7.1 (ver plan §9.4) -- null es la interpretacion
// conservadora, nunca una industria inventada.
export const BUSINESS_TAXONOMY: BusinessTaxonomyEntry[] = [
  {
    key: "hospitality",
    label: "Hospitality (Hotels & Resorts)",
    synonyms: ["hotel", "hoteles", "resort", "resorts", "lodging", "hospitality", "hospitalidad", "motel", "inn"],
    companyTypes: ["hotel", "resort", "lodging property", "motel", "inn"],
    crmIndustryBucket: null,
    googleSearchPhrases: ["hotel", "resort", "lodging property", "hospitality group"],
    websitePhrases: ["rooms", "reservations", "check-in", "housekeeping", "hospitality"],
    jobTitles: [
      "Housekeeper",
      "Room Attendant",
      "Housekeeping",
      "Laundry Attendant",
      "Cleaning Staff",
      "Front Desk Agent",
    ],
    decisionMakers: ["General Manager", "Executive Housekeeper", "Housekeeping Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["staffing agency", "recruiting agency", "travel agency"],
    relatedIndustries: ["janitorial", "commercial_cleaning"],
    validations: [
      "El sitio menciona reservas/habitaciones/check-in",
      "El nombre incluye Hotel/Resort/Inn/Motel o equivalente",
    ],
    version: 1,
  },
  {
    key: "manufacturing",
    label: "Manufacturing (General)",
    synonyms: [
      "manufacturing",
      "manufactura",
      "manufacturera",
      "manufacturero",
      "fabrica",
      "fabricas",
      "planta industrial",
      "plantas industriales",
      "industrial plant",
      "factory",
    ],
    companyTypes: ["manufacturing company", "factory", "industrial plant"],
    crmIndustryBucket: "Manufacturing",
    googleSearchPhrases: ["manufacturing company", "factory", "industrial manufacturer"],
    websitePhrases: ["production line", "manufacturing facility", "plant", "quality control"],
    jobTitles: ["Production Worker", "Machine Operator", "Maintenance Technician", "Quality Control Inspector"],
    decisionMakers: ["Plant Manager", "Operations Manager", "Production Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["staffing agency", "logistics only", "pure distribution"],
    relatedIndustries: ["food_manufacturing", "beverage_manufacturing", "packaging", "industrial_automation"],
    validations: ["El sitio muestra evidencia real de producción/planta", "No es una oficina corporativa sin planta"],
    version: 1,
  },
  {
    key: "food_manufacturing",
    label: "Food Manufacturing",
    synonyms: [
      "food manufacturing",
      "food processing",
      "food processor",
      "fabricantes de alimentos",
      "fabricas de alimentos",
      "empresas manufactureras de alimentos",
      "bakery manufacturer",
      "dairy processing",
      "meat processing",
    ],
    companyTypes: ["food manufacturer", "food processing plant", "bakery manufacturer", "dairy processor"],
    crmIndustryBucket: "Manufacturing",
    googleSearchPhrases: ["food manufacturing company", "food processing plant", "food production facility"],
    websitePhrases: ["food safety", "FDA", "HACCP", "food production"],
    jobTitles: ["Production Worker", "Machine Operator", "Food Safety Technician", "Sanitation Worker"],
    decisionMakers: ["Plant Manager", "Production Manager", "Operations Manager", "HR Manager"],
    negativeKeywords: ["restaurant", "grocery store", "distributor only"],
    relatedIndustries: ["manufacturing", "beverage_manufacturing", "packaging"],
    validations: ["El sitio menciona producción/procesamiento de alimentos, no solo venta"],
    version: 1,
  },
  {
    key: "beverage_manufacturing",
    label: "Beverage Manufacturing",
    synonyms: [
      "beverage manufacturing",
      "beverage plant",
      "fabricas de bebidas",
      "fabricante de bebidas",
      "bottling plant",
      "brewery",
      "cervecera",
    ],
    companyTypes: ["beverage manufacturer", "bottling plant", "brewery", "beverage plant"],
    crmIndustryBucket: "Manufacturing",
    googleSearchPhrases: ["beverage manufacturing company", "bottling plant", "brewery"],
    websitePhrases: ["bottling", "brewing", "beverage production"],
    jobTitles: ["Production Worker", "Machine Operator", "Bottling Line Operator"],
    decisionMakers: ["Plant Manager", "Production Manager", "Operations Manager", "HR Manager"],
    negativeKeywords: ["bar", "restaurant", "liquor store"],
    relatedIndustries: ["food_manufacturing", "manufacturing", "packaging"],
    validations: ["El sitio muestra evidencia de producción/embotellado, no solo venta al público"],
    version: 1,
  },
  {
    key: "packaging",
    label: "Packaging",
    synonyms: ["packaging", "empaques", "empaquetado", "packaging company", "packaging manufacturer"],
    companyTypes: ["packaging manufacturer", "packaging company"],
    crmIndustryBucket: "Manufacturing",
    googleSearchPhrases: ["packaging manufacturing company", "packaging plant"],
    websitePhrases: ["packaging solutions", "corrugated", "co-packing"],
    jobTitles: ["Production Worker", "Machine Operator", "Packaging Line Worker"],
    decisionMakers: ["Plant Manager", "Operations Manager", "Production Manager", "HR Manager"],
    negativeKeywords: ["shipping only", "retail packaging store"],
    relatedIndustries: ["manufacturing", "food_manufacturing", "beverage_manufacturing"],
    validations: ["El sitio muestra evidencia de fabricación de empaques, no solo distribución"],
    version: 1,
  },
  {
    key: "warehousing",
    label: "Warehousing",
    synonyms: ["warehouse", "warehouses", "warehousing", "almacen", "almacenes", "bodega"],
    companyTypes: ["warehouse", "warehousing company", "fulfillment center"],
    crmIndustryBucket: "Warehouse/Logistics",
    googleSearchPhrases: ["warehouse company", "warehousing and fulfillment", "distribution warehouse"],
    websitePhrases: ["warehouse", "fulfillment", "storage facility"],
    jobTitles: ["Forklift Operator", "Warehouse Associate", "Material Handler", "Order Picker"],
    decisionMakers: ["Warehouse Manager", "Operations Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["retail store", "office only"],
    relatedIndustries: ["distribution", "transportation", "manufacturing"],
    validations: ["El sitio muestra evidencia de operación de almacén/fulfillment"],
    version: 1,
  },
  {
    key: "distribution",
    label: "Distribution & Logistics",
    synonyms: ["distribution", "distribucion", "logistics", "logistica", "distribution center"],
    companyTypes: ["distribution company", "logistics company", "distribution center"],
    crmIndustryBucket: "Warehouse/Logistics",
    googleSearchPhrases: ["distribution company", "logistics company", "distribution center"],
    websitePhrases: ["distribution center", "supply chain", "logistics"],
    jobTitles: ["Forklift Operator", "Warehouse Associate", "Material Handler", "Delivery Driver"],
    decisionMakers: ["Operations Manager", "Warehouse Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["pure manufacturing only"],
    relatedIndustries: ["warehousing", "transportation"],
    validations: ["El sitio muestra evidencia de operación de distribución/logística"],
    version: 1,
  },
  {
    key: "healthcare",
    label: "Healthcare Facilities",
    synonyms: ["hospital", "hospitales", "healthcare", "clinic", "clinica", "medical center", "nursing home"],
    companyTypes: ["hospital", "clinic", "medical center", "nursing home", "healthcare facility"],
    crmIndustryBucket: null,
    googleSearchPhrases: ["hospital", "medical center", "healthcare facility", "nursing home"],
    websitePhrases: ["patient care", "medical center", "emergency room"],
    jobTitles: [
      "Environmental Services",
      "Environmental Services Technician",
      "Housekeeping",
      "Custodian",
      "personal de limpieza",
    ],
    decisionMakers: ["Environmental Services Director", "Facilities Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["staffing agency", "insurance company"],
    relatedIndustries: ["janitorial", "commercial_cleaning"],
    validations: ["El sitio muestra evidencia real de atención médica/paciente"],
    version: 1,
  },
  {
    key: "janitorial",
    label: "Janitorial Services",
    synonyms: ["janitorial", "janitorial services", "servicios de limpieza", "limpieza comercial"],
    companyTypes: ["janitorial services company", "cleaning services company"],
    crmIndustryBucket: null,
    googleSearchPhrases: ["janitorial services company", "commercial cleaning company"],
    websitePhrases: ["janitorial", "commercial cleaning", "facility maintenance"],
    jobTitles: ["Janitor", "Custodian", "Cleaning Technician"],
    decisionMakers: ["Owner", "President", "Operations Manager", "Branch Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["staffing agency", "residential cleaning only"],
    relatedIndustries: ["commercial_cleaning", "hospitality", "healthcare"],
    validations: ["El sitio ofrece servicios de limpieza comercial reales, no es un cliente de limpieza"],
    version: 1,
  },
  {
    key: "commercial_cleaning",
    label: "Commercial Cleaning",
    synonyms: ["commercial cleaning", "limpieza comercial", "cleaning company", "facility services"],
    companyTypes: ["commercial cleaning company", "facility services company"],
    crmIndustryBucket: null,
    googleSearchPhrases: ["commercial cleaning company", "facility services company"],
    websitePhrases: ["commercial cleaning", "facility services", "office cleaning"],
    jobTitles: ["Janitor", "Custodian", "Cleaning Technician"],
    decisionMakers: ["Owner", "President", "Operations Manager", "Branch Manager", "HR Manager"],
    negativeKeywords: ["staffing agency", "residential cleaning only"],
    relatedIndustries: ["janitorial"],
    validations: ["El sitio ofrece servicios de limpieza comercial reales"],
    version: 1,
  },
  {
    key: "construction",
    label: "Construction (General)",
    synonyms: ["construction", "construccion", "contractor", "contratista", "builder"],
    companyTypes: ["construction company", "general contractor", "builder"],
    crmIndustryBucket: "Construction",
    googleSearchPhrases: ["construction company", "general contractor"],
    websitePhrases: ["construction services", "general contractor", "projects completed"],
    jobTitles: ["Laborer", "Carpenter", "Project Manager"],
    decisionMakers: ["Owner", "President", "Project Manager", "Operations Manager", "HR Manager"],
    negativeKeywords: ["staffing agency", "real estate agency"],
    relatedIndustries: ["roofing", "electrical", "industrial_automation"],
    validations: ["El sitio muestra proyectos reales de construcción"],
    version: 1,
  },
  {
    key: "roofing",
    label: "Roofing Contractors",
    synonyms: ["roofing", "roofers", "roofing contractor", "techos", "techado"],
    companyTypes: ["roofing contractor", "roofing company"],
    crmIndustryBucket: "Construction",
    googleSearchPhrases: ["roofing contractor", "roofing company"],
    websitePhrases: ["roofing services", "roof repair", "roof installation"],
    jobTitles: ["Roofer", "Laborer", "Installer"],
    decisionMakers: ["Owner", "President", "Operations Manager", "Project Manager", "HR Manager"],
    negativeKeywords: ["staffing agency", "real estate agency"],
    relatedIndustries: ["construction"],
    validations: ["El sitio ofrece servicios de techado reales"],
    version: 1,
  },
  {
    key: "electrical",
    label: "Electrical Contractors",
    synonyms: ["electrical contractor", "electricians", "electricistas", "electrical company", "electrical services"],
    companyTypes: ["electrical contractor", "electrical services company"],
    crmIndustryBucket: "Construction",
    googleSearchPhrases: ["electrical contractor", "electrical services company"],
    websitePhrases: ["electrical services", "licensed electrician", "electrical contractor"],
    jobTitles: ["Electrician", "Electricista", "Apprentice Electrician", "Journeyman Electrician"],
    decisionMakers: ["Owner", "President", "Operations Manager", "Project Manager", "HR Manager"],
    negativeKeywords: ["staffing agency", "electronics retail store"],
    relatedIndustries: ["construction", "industrial_automation", "data_centers"],
    validations: ["El sitio ofrece servicios eléctricos contratados reales"],
    version: 1,
  },
  {
    key: "industrial_automation",
    label: "Industrial Automation",
    synonyms: [
      "industrial automation",
      "automatizacion industrial",
      "controls contractor",
      "automation integrator",
    ],
    companyTypes: ["industrial automation company", "controls contractor", "automation integrator"],
    crmIndustryBucket: "Construction",
    googleSearchPhrases: ["industrial automation company", "controls contractor", "automation integrator"],
    websitePhrases: ["industrial automation", "controls integration", "PLC programming"],
    jobTitles: ["Controls Technician", "Maintenance Technician", "Automation Technician"],
    decisionMakers: ["Owner", "President", "Operations Manager", "Project Manager", "HR Manager"],
    negativeKeywords: ["staffing agency", "software company only"],
    relatedIndustries: ["manufacturing", "electrical", "data_centers"],
    validations: ["El sitio ofrece integración/automatización industrial real"],
    version: 1,
  },
  {
    key: "data_centers",
    label: "Data Centers",
    synonyms: ["data center", "data centers", "colocation", "hyperscale", "critical facilities"],
    companyTypes: ["data center operator", "colocation facility", "critical facilities contractor"],
    crmIndustryBucket: "Construction",
    googleSearchPhrases: ["data center construction", "colocation facility", "hyperscale data center construction"],
    websitePhrases: ["data center", "colocation", "uptime", "critical facilities"],
    jobTitles: ["Electrician", "Electricista", "Data Center Technician", "Maintenance Technician"],
    decisionMakers: ["Facilities Manager", "Operations Manager", "Project Manager", "HR Manager"],
    negativeKeywords: ["staffing agency", "software/cloud company only (no physical facility)"],
    relatedIndustries: ["mission_critical", "electrical", "industrial_automation"],
    validations: ["El sitio muestra evidencia de una instalación física real de data center"],
    version: 1,
  },
  {
    key: "mission_critical",
    label: "Mission Critical Facilities",
    synonyms: ["mission critical", "mission critical contractor", "mission critical facilities"],
    companyTypes: ["mission critical contractor", "critical facilities company"],
    crmIndustryBucket: "Construction",
    googleSearchPhrases: ["mission critical construction", "mission critical contractor", "critical facilities contractor"],
    websitePhrases: ["mission critical", "critical facilities", "uptime"],
    jobTitles: ["Electrician", "Maintenance Technician", "Facilities Technician"],
    decisionMakers: ["Facilities Manager", "Operations Manager", "Project Manager", "HR Manager"],
    negativeKeywords: ["staffing agency"],
    relatedIndustries: ["data_centers", "electrical", "industrial_automation"],
    validations: ["El sitio muestra evidencia real de instalaciones críticas/mission critical"],
    version: 1,
  },
  {
    key: "landscaping",
    label: "Landscaping",
    synonyms: ["landscaping", "landscaping company", "jardineria", "paisajismo", "lawn care"],
    companyTypes: ["landscaping company", "lawn care company"],
    crmIndustryBucket: null,
    googleSearchPhrases: ["landscaping company", "lawn care company"],
    websitePhrases: ["landscaping services", "lawn care", "grounds maintenance"],
    jobTitles: ["Groundskeeper", "Landscape Laborer", "Crew Leader"],
    decisionMakers: ["Owner", "President", "Operations Manager", "Branch Manager", "HR Manager"],
    negativeKeywords: ["staffing agency", "garden retail store"],
    relatedIndustries: ["construction"],
    validations: ["El sitio ofrece servicios de paisajismo/jardinería reales"],
    version: 1,
  },
  {
    key: "restaurants",
    label: "Restaurants",
    synonyms: ["restaurant", "restaurantes", "restaurant group", "dining", "food service establishment"],
    companyTypes: ["restaurant", "restaurant group", "dining establishment"],
    crmIndustryBucket: null,
    googleSearchPhrases: ["restaurant", "restaurant group"],
    websitePhrases: ["menu", "reservations", "dining"],
    jobTitles: ["Dishwasher", "Line Cook", "Server", "Host"],
    decisionMakers: ["General Manager", "Owner", "HR Manager", "Recruiter"],
    negativeKeywords: ["staffing agency", "food manufacturer", "grocery store"],
    relatedIndustries: ["food_manufacturing"],
    validations: ["El sitio muestra un menú/servicio de comida real al público"],
    version: 1,
  },
  {
    key: "retail",
    label: "Retail",
    synonyms: ["retail", "retail store", "tienda", "comercio minorista", "retailer"],
    companyTypes: ["retail store", "retailer", "retail chain"],
    crmIndustryBucket: null,
    googleSearchPhrases: ["retail store", "retail chain"],
    websitePhrases: ["store locations", "shop", "retail"],
    jobTitles: ["Sales Associate", "Cashier", "Store Manager"],
    decisionMakers: ["Store Manager", "District Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["staffing agency", "wholesale distributor only"],
    relatedIndustries: ["distribution"],
    validations: ["El sitio muestra tiendas/ubicaciones de venta al público reales"],
    version: 1,
  },
  {
    key: "transportation",
    label: "Transportation & Trucking",
    synonyms: ["transportation", "transporte", "trucking", "trucking company", "freight carrier"],
    companyTypes: ["trucking company", "freight carrier", "transportation company"],
    crmIndustryBucket: "Warehouse/Logistics",
    googleSearchPhrases: ["trucking company", "freight carrier", "transportation company"],
    websitePhrases: ["fleet", "freight", "trucking services"],
    jobTitles: ["Truck Driver", "CDL Driver", "Dispatcher", "Warehouse Associate"],
    decisionMakers: ["Operations Manager", "Fleet Manager", "HR Manager", "Recruiter"],
    negativeKeywords: ["staffing agency", "car dealership"],
    relatedIndustries: ["warehousing", "distribution"],
    validations: ["El sitio muestra evidencia real de flota/operación de transporte"],
    version: 1,
  },
];

export function getTaxonomyEntry(key: string): BusinessTaxonomyEntry | undefined {
  return BUSINESS_TAXONOMY.find((entry) => entry.key === key);
}
